#!/bin/python3

import os
import sys

#
# Complete the simpleArraySum function below.
#
def simpleArraySum(ar,n):
    if len(ar)==1:
        return ar[0]
    else:
        return ar[0]+simpleArraySum(ar[1:],n)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ar_count = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = simpleArraySum(ar,ar_count)

    fptr.write(str(result) + '\n')

    fptr.close()
