#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    ne=0
    p=0
    z=0
    for i in range(n):
        if(arr[i]>0):
            p+=1
        elif(arr[i]<0):
            ne+=1
        else:
            z+=1
        
    a=float(p/n)
    b=float(ne/n)
    c=float(z/n)

    print(a,b,c,sep="\n")

if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
    
